var F=0,g={components:[],check:function(){g.components.forEach(t=>{document.contains(t.node)||t.exit()})},add:function(t,i){this.components.indexOf(t)>-1||(this.components.push(t),t.exit=i)}},H="number string undefined".split(" "),R=t=>{if(!H.includes(typeof t))throw`Argument is not an string, number or undefined : '${t}' in primitiveDispatcher() method.`},j=t=>{if(!Array.isArray(t))throw`Argument is not an array: '${t}' in arrayDispacher() method.`},b=Symbol("firstTime"),S=Symbol("stateIndex"),E=Symbol("defaultStateDone"),D=Symbol("setProperties"),_=Symbol("addChild"),d=Symbol("children"),v=Symbol("subComponent"),T=Symbol("listeners"),A=Symbol("settingListener"),N=Symbol("exec"),k=Symbol("refresh"),w=Symbol("re-render"),f=Symbol("useEffectCallbacks"),y=Symbol("useEffectCallbacksPrev"),L=Symbol("runSideEffects"),C=Symbol("hookBehaviour"),q={runAsHook:function(){this[C]=!0,this[S]=0},useEffect:function(t,i=[],e){let n=JSON.stringify(i);this[f][this.id]||(this[f][this.id]=[]);let o=this[f][this.id].length;if(this[f][this.id].push([t,n]),this[y][o]!=n&&this[C]){this[y][o]=n;let s=t();typeof s=="function"&&g.add(this,s)}},beforeAppendChild:function(t){},prop:{},noProp:["beforeAppendChild","prop","enableSubComponents","enableEvents","kiwiSelector","useState","noProp"],enableSubComponents:function(t){if(Array.isArray(t))throw"this.enableSubComponents() only allow Objects but not allows arrays."+`
`+this.constructor;this[v]=t},enableEvents:function(t){this[T]=Array.isArray(t)?t:[t]},kiwiSelector:function(t){let i=this[N]();document.querySelector(t).appendChild(i)},useState:function(t){let i=t;this.state||(this.state={});let e=this[S]++;return this[E]?i=this.state[e]:this.state[e]=i,[typeof i=="undefined"?i:JSON.parse(JSON.stringify(this.state[e])),n=>{typeof this.state[e]=="object"&&Object.assign(this.state[e],typeof n=="function"?n():n),this.state[e]=n,this[C]&&(this[S]=0,this[E]=!0),this[w](),g.check()}]},useReducer:function(t,i={}){return this[E]||(this.state=i),[this.state,e=>{this.state=t(this.state,e),this[w]()}]},arrayDispatcher:function(t=[]){j(t);let i=[];return[{get items(){return[...t]},subscribe:function(o){i.push(o)}},o=>{j(t),t.length=0,o.forEach(s=>{t.push(s)}),i.forEach(s=>s([...t]))},[...t]]},variableDispatcher:function(t){R(t);let i=[],e=t;return[{get value(){return e},subscribe:function(s){i.push(s)}},s=>{R(s),e=s,i.forEach(r=>r(s))},e]}},M=function(){return this[C]=!1,this[L]=function(t){!this[f][this.id]||(this[f][this.id].forEach((i,e)=>{if(this[y][e]!=i[1]){this[y][e]=i[1];let n=i[0](t);typeof n=="function"&&g.add(this,n)}}),this[f][this.id]=[])},this[f]={},this[y]=[],this[b]=!0,this[S]=0,this[E]=!1,this[D]=function(t){let i={};for(let e=0;e<t.length;e++)if(typeof this[t[e].value]=="function")i[t[e].name]=this.noProp.includes(t[e].value)?t[e].value:this[t[e].value](),this.noProp.includes(t[e].value)&&console.warn(`Atttribute Value '${t[e].value}' as string due it is a reserved keyword`);else try{i[t[e].name]=JSON.parse(t[e].value)}catch{i[t[e].name]=t[e].value}return i},this[_]=function(t){return Object.keys(this[v]).map(i=>{let e=this[v][i],n=t.querySelectorAll(i.toLowerCase());this[d]=this[d]||[],this[d].forEach(o=>{o.free=!0});for(let o=0;o<n.length;o++){let s=n[o],r=this[D](s.attributes),l=null,h=0,c=!1;for(h=0;h<this[d].length;h++){let m=this[d][h];if(m.instanceComponet.constructor.name==i&&!!m.free){l=m.instanceComponet,c=!0,this[d][h]={free:!1,instanceComponet:m.instanceComponet};break}}let u=c?l:x(e);c||(this[d][o]={free:!1,instanceComponet:u}),u.prop={},Object.assign(u.prop,r);let O=u[N]();s.parentNode.replaceChild(O,s)}}),t},this[v]=[],this[T]=[],this[A]=function(t,i=null){this[T].map(e=>{let n=t.querySelectorAll("["+e+"]");for(let o=0;o<n.length;o++){let s=n[o],r=s.getAttribute(e);if(!r)throw"There is no attribute '"+e+`' value on:

`+s.outerHTML;i?s.removeEventListener(e,this[r]):s.addEventListener(e,this[r])}})},this[k]=function(t,i){let e=!0;function n(r,l){let h=!1;r.lenght==l.lenght&&r.forEach((c,u)=>{if(c.textContent!=l[u].textContent){if(c.nodeName!=l[u].nodeName)return;c.childNodes[0]&&l[u].childNodes[0]?c.childNodes[0].textContent=l[u].childNodes[0].textContent:c.textContent=l[u].textContent,e=!1,h=!0}}),h||(e=!1)}let o=t.querySelectorAll("*"),s=i.querySelectorAll("*");if(o.length!=i.querySelectorAll("*").length)return!0;o.forEach((r,l)=>{r.tagName!=s[l].tagName&&r.parentNode.replaceChild(s[l].cloneNode(!0),r)});try{o.forEach((r,l)=>{let h=s[l],c={};for(let a of r.attributes)c[a.name]=a.value;for(let a of h.attributes)c[a.name]=a.value;let u=!1;if(Object.keys(c).forEach(a=>{h.getAttribute(a)==null?(r.removeAttribute(a),u=!0):r.getAttribute(a)!=h.getAttribute(a)&&(r.setAttribute(a,h.getAttribute(a)),u=!0)}),u)return!1;let O=r.childNodes,m=h.childNodes;n(O,m)})}catch(r){console.error("SOMETHING WRONG: ",r)}return e},this[w]=function(){try{let t=this.node,i=this.node.parentNode;this[A](this.node.parentNode,!0);let e=this[N](!0);this[k](t,e)?t.parentNode.replaceChild(e,t):(this.node=t,this[A](i)),this[L](i)}catch{}},this[N]=function(t){var i=document.createElement("section");this[S]=0,Array.prototype.toString=function(){return this.join("")};let e=this.constructor(this.prop);if(this[C])return e;let n=e.split("/>");if(n.length>1){let s=n.pop(),r=n.map(l=>{let h=l.split("<"),u=h[h.length-1].split(" ")[0];return l+`></${u}>`});r.push(s),e=r.join("")}Array.prototype.toString=function(){return this.join(",")},this[E]=!0,i.innerHTML=e,this[A](i),this[_](i);let o=this[b];if(this[b]&&(this[b]=!1,this.beforeAppendChild(i)),o&&this[L](i),this.node=i.children[0],!this.node)throw`Check the return of ${this.constructor.name}
${this.constructor.toString()}`;return this.node},this},p=M.bind(q)();function $(){}var x=t=>{let i=new $,e=n=>{i[n]=typeof p[n]=="object"?Array.isArray(p[n])?[]:{}:typeof p[n]=="function"?p[n].bind(i):p[n]};return Object.keys(p).map(e),Object.getOwnPropertySymbols(p).forEach(e),i.constructor=t,i[b]&&(i.id=F++),i},I=x;function U({variable:t}){let[i,e]=this.useState(t.value);this.beforeAppendChild=()=>{t.subscribe(()=>{e(t.value)})};var n=new remarkable.Remarkable;return`
        <div class="content">
            ${n.render(i)}
        </div>`}function P(){this.enableEvents(["keyup"]);let[t,i,e]=this.variableDispatcher("Hello, **world**!");return this.handleChange=n=>{i(n.target.value)},this.enableSubComponents({Output:U}),this.variableProvider=()=>t,`
        <div class="MarkdownEditor">
            <h3>Input</h3>
            <label for="markdown-content">
                Enter some markdown
            </label><br/>
            <textarea  id="markdown-content" 
                keyup="handleChange">${e}</textarea>
            <h3>Output</h3>
            <Output variable="variableProvider"></Output>
        </div>`}I(P).kiwiSelector("body");export{P as default};
